#pragma once

#define VRAM_BEGIN                     ((volatile int *) 0x00040000)
#define VRAM_DISPLAY_BEGIN             (VRAM_BEGIN)
#define VRAM_DISPLAY_N                 (8)
#define VRAM_DISPLAY(INDEX)            (VRAM_DISPLAY_BEGIN + (INDEX))
#define VRAM_DISPLAY_END               (VRAM_DISPLAY_BEGIN + VRAM_DISPLAY_N)
#define VRAM_DISPLAY_0                 (VRAM_DISPLAY(0))
#define VRAM_DISPLAY_1                 (VRAM_DISPLAY(1))
#define VRAM_DISPLAY_2                 (VRAM_DISPLAY(2))
#define VRAM_DISPLAY_3                 (VRAM_DISPLAY(3))
#define VRAM_DISPLAY_4                 (VRAM_DISPLAY(4))
#define VRAM_DISPLAY_5                 (VRAM_DISPLAY(5))
#define VRAM_DISPLAY_6                 (VRAM_DISPLAY(6))
#define VRAM_DISPLAY_7                 (VRAM_DISPLAY(7))
#define VRAM_DISPLAY_SET(INDEX, VALUE) (*VRAM_DISPLAY(INDEX) = (int) (VALUE))

#define VRAM_LINE_DEVICE_BEGIN      (VRAM_BEGIN + 0x40)
#define VRAM_LINE_DEVICE_CHAR_ADDR  (VRAM_LINE_DEVICE_BEGIN)
#define VRAM_LINE_DEVICE_CLEAR_ADDR (VRAM_LINE_DEVICE_BEGIN + 1)

#define VRAM_PX_BEGIN               (VRAM_BEGIN + 0x100)
#define VRAM_PX_WIDTH               (32)
#define VRAM_PX_HEIGHT              (32)
#define VRAM_PX_N                   (VRAM_PX_DEVICE_WIDTH * VRAM_PX_DEVICE_HEIGHT)
#define VRAM_PX(INDEX)              (VRAM_PX_DEVICE_BEGIN + (INDEX))
#define VRAM_PX_BUFFERS_BEGIN       (VRAM_PX_BEGIN)
#define VRAM_PX_B1_BEGIN            (VRAM_PX_BUFFERS_BEGIN)
#define VRAM_PX_B1_END              (VRAM_PX_B1_BEGIN + VRAM_PX_N)
#define VRAM_PX_B2_BEGIN            (VRAM_PX_B1_END)
#define VRAM_PX_B2_END              (VRAM_PX_B2_BEGIN + VRAM_PX_N)
#define VRAM_PX_BUFFERS_END         (VRAM_PX_B2_END)
#define VRAM_PX_CONTROL_BEGIN       (VRAM_PX_BUFFERS_END)
#define VRAM_PX_CONTROL_N           (3)
#define VRAM_PX_CONTROL_CLEAR       (VRAM_PX_CONTROL_BEGIN + 0)
#define VRAM_PX_CONTROL_SET         (VRAM_PX_CONTROL_BEGIN + 1)
#define VRAM_PX_CONTROL_SWAP_BUFFER (VRAM_PX_CONTROL_BEGIN + 2)
#define VRAM_PX_CONTROL_END         (VRAM_PX_CONTROL_BEGIN + VRAM_PX_CONTROL_N)