#!/bin/bash
echo "Making vcd."
rm tb_obj 2> /dev/null
rm *.vcd 2> /dev/null

set -e

iverilog -o tb_obj *tb.v -Wall \
	-y ../core/riscv \
	-y ../../../v2flib/ \
	-y . \
	-I ../core/riscv \
	-I ./char_display \
	-I ../../../v2flib/ \
		&& vvp tb_obj
